/**
 * OpenAPI/Scalar contract (docs/daemon-api.md): mounts the real daemon app and
 * asserts the generated spec at `/openapi/json` and the interactive UI at
 * `/openapi`.
 *
 * The spec is generated by `@elysiajs/openapi` from the routes' `detail`
 * metadata at registration time — no handler runs, so this test is transport-
 * and filesystem-light (it still uses a throwing/empty memory store where a
 * route needs one). It locks:
 *
 *   - the docs surface is reachable WITHOUT the bearer token while every API
 *     route stays 401-gated;
 *   - every operation has a stable, unique `operationId`, a declared tag, and a
 *     typed `200`;
 *   - the exact route set (a drift guard — bump the expected list when the API
 *     grows);
 *   - path/query parameters and request bodies are documented where the
 *     handlers read them.
 */

import { describe, expect, test } from "bun:test"
import { MemoryStore, NoopEventSink } from "../../../src/engine/index.ts"
import { createDaemonApp, docsTrailingSlashRedirect, isDocsPath, type DaemonInfo } from "../../../src/daemon/index.ts"

const TOKEN = "0123456789abcdef0123456789abcdef"

function makeInfo(): DaemonInfo {
  return {
    ok: true,
    name: "sensus-daemon",
    version: "9.9.9",
    pid: 4242,
    platform: "linux",
    startedAt: 1_000_000,
    uptimeMs: 1234,
    socket: "/run/user/1000/sensus-1000/daemon.sock",
    tcp: { host: "127.0.0.1", port: 54321 },
    shells: 0,
    persistent: false,
    instance: { instanceId: "test-instance", createdAt: 1, version: "9.9.9" },
  }
}

function makeApp() {
  return createDaemonApp({
    token: TOKEN,
    version: "9.9.9",
    info: makeInfo,
    memory: () => new MemoryStore({ dir: "/nonexistent-sensus-openapi-test", limits: { memory: 1, host: 1, journal: 1 } }),
    events: new NoopEventSink(),
    config: () => ({}),
    sessionsDataDir: "/nonexistent-sensus-openapi-test",
  })
}

interface Schema {
  type?: string
  $ref?: string
  properties?: Record<string, unknown>
  items?: Schema
  required?: string[]
  enum?: unknown[]
  anyOf?: Schema[]
  oneOf?: Schema[]
  allOf?: Schema[]
  content?: Record<string, { schema?: Schema }>
}

interface Operation {
  operationId?: string
  tags?: string[]
  summary?: string
  description?: string
  parameters?: Array<{ name: string; in: string; required?: boolean; schema?: Schema }>
  requestBody?: { content?: Record<string, { schema?: Schema }> }
  responses?: Record<string, { description?: string; content?: Record<string, { schema?: Schema }> }>
}

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const

function operations(spec: { paths?: Record<string, Record<string, Operation>> }): Array<{ path: string; method: string; op: Operation }> {
  const out: Array<{ path: string; method: string; op: Operation }> = []
  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      const op = methods[method]
      if (op) out.push({ path, method, op })
    }
  }
  return out
}

/** True when a schema describes something (not an empty `{}` placeholder). */
function isTyped(schema: Schema | undefined): boolean {
  if (schema === undefined) return false
  if (schema.$ref || schema.type || schema.items) return true
  if (schema.properties && Object.keys(schema.properties).length > 0) return true
  if (schema.enum && schema.enum.length > 0) return true
  for (const variant of [...(schema.anyOf ?? []), ...(schema.oneOf ?? []), ...(schema.allOf ?? [])]) {
    if (isTyped(variant)) return true
  }
  return false
}

describe("daemon OpenAPI/Scalar documentation", () => {
  test("isDocsPath recognizes the docs surface only", () => {
    expect(isDocsPath("/openapi")).toBe(true)
    expect(isDocsPath("/openapi/json")).toBe(true)
    expect(isDocsPath("/openapi/anything")).toBe(true)
    expect(isDocsPath("/v1/openapi")).toBe(false)
    expect(isDocsPath("/v1/health")).toBe(false)
    expect(isDocsPath("/")).toBe(false)
  })

  test("a trailing-slash docs URL canonicalises to /openapi (the Scalar spec URL is relative)", async () => {
    expect(docsTrailingSlashRedirect(new URL("http://h/openapi/"))).toBe("http://h/openapi")
    expect(docsTrailingSlashRedirect(new URL("http://h/openapi/"))).not.toBe("http://h/openapi/")
    expect(docsTrailingSlashRedirect(new URL("http://h/openapi"))).toBeNull()
    expect(docsTrailingSlashRedirect(new URL("http://h/openapi/json"))).toBeNull()
    expect(docsTrailingSlashRedirect(new URL("http://h/base/openapi/"))).toBeNull()

    const res = await makeApp().handle(new Request("http://localhost/openapi/"))
    expect(res.status).toBe(308)
    expect(res.headers.get("location")).toBe("http://localhost/openapi")
    // The canonical URL still serves the UI.
    expect((await makeApp().handle(new Request("http://localhost/openapi"))).status).toBe(200)
  })

  test("Scalar UI + spec are reachable without a token; API routes stay 401", async () => {
    const app = makeApp()

    const ui = await app.handle(new Request("http://localhost/openapi"))
    expect(ui.status).toBe(200)
    expect(ui.headers.get("content-type")).toContain("text/html")
    expect((await ui.text()).toLowerCase()).toContain("scalar")

    const specRes = await app.handle(new Request("http://localhost/openapi/json"))
    expect(specRes.status).toBe(200)
    expect(specRes.headers.get("content-type")).toContain("application/json")
    const spec = (await specRes.json()) as { paths?: Record<string, Record<string, Operation>> }

    // Every documented route is still bearer-gated (using the route's own
    // method: a POST-only path has no GET handler to carry the auth hook).
    for (const { path, method } of operations(spec)) {
      const res = await app.handle(new Request(`http://localhost${path}`, { method: method.toUpperCase() }))
      expect(res.status, `${method.toUpperCase()} ${path} should be 401 without a token`).toBe(401)
    }
  })

  test("spec carries the info, servers and bearer security scheme", async () => {
    const spec = (await (await makeApp().handle(new Request("http://localhost/openapi/json"))).json()) as {
      info: { title: string; version: string; description: string; license?: { identifier?: string } }
      servers: Array<{ url: string }>
      security: unknown[]
      tags: Array<{ name: string }>
      components: { securitySchemes: Record<string, { type: string; scheme: string }> }
    }
    expect(spec.info.title).toBe("Sensus daemon API")
    expect(spec.info.version).toBe("9.9.9")
    expect(spec.info.description).toContain("Authorization: Bearer")
    expect(spec.info.license?.identifier).toBe("Apache-2.0")
    expect(spec.servers[0]?.url).toBe("/")
    expect(spec.security).toEqual([{ bearerAuth: [] }])
    expect(spec.components.securitySchemes.bearerAuth).toMatchObject({ type: "http", scheme: "bearer" })
    expect(spec.tags.map((t) => t.name)).toEqual([
      "core",
      "config",
      "agents",
      "skills",
      "memory",
      "sessions",
      "audit",
      "mcp",
      "models",
      "usage",
    ])
  })

  test("every operation has a stable, unique operationId, a declared tag, and a typed 200", async () => {
    const app = makeApp()
    const spec = (await (await app.handle(new Request("http://localhost/openapi/json"))).json()) as {
      paths?: Record<string, Record<string, Operation>>
      tags: Array<{ name: string }>
    }
    const declared = new Set(spec.tags.map((t) => t.name))
    const ops = operations(spec)
    expect(ops.length).toBeGreaterThanOrEqual(20)

    const seen = new Set<string>()
    for (const { path, method, op } of ops) {
      expect(op.operationId, `${method.toUpperCase()} ${path} missing operationId`).toBeTypeOf("string")
      expect((op.operationId ?? "").length).toBeGreaterThan(0)
      expect(seen.has(op.operationId as string), `duplicate operationId ${op.operationId}`).toBe(false)
      seen.add(op.operationId as string)

      expect(Array.isArray(op.tags) && op.tags.length > 0, `${method.toUpperCase()} ${path} has no tag`).toBe(true)
      for (const tag of op.tags ?? []) expect(declared.has(tag), `${path} uses undeclared tag ${tag}`).toBe(true)

      expect(op.summary, `${method.toUpperCase()} ${path} missing summary`).toBeTypeOf("string")
      expect(op.description, `${method.toUpperCase()} ${path} missing description`).toBeTypeOf("string")

      const ok = op.responses?.["200"]
      expect(ok, `${method.toUpperCase()} ${path} missing a 200 response`).toBeDefined()
      const schemas = Object.values(ok?.content ?? {}).map((media) => media.schema)
      expect(schemas.length, `${method.toUpperCase()} ${path} 200 has no content`).toBeGreaterThan(0)
      expect(schemas.some(isTyped), `${method.toUpperCase()} ${path} 200 schema is empty`).toBe(true)

      // Every API route documents the 401 failure.
      expect(op.responses?.["401"], `${method.toUpperCase()} ${path} missing 401`).toBeDefined()
    }
  })

  test("the documented route set matches the daemon surface", async () => {
    const spec = (await (await makeApp().handle(new Request("http://localhost/openapi/json"))).json()) as {
      paths?: Record<string, Record<string, Operation>>
    }
    const actual = operations(spec)
      .map(({ path, method }) => `${method.toUpperCase()} ${path}`)
      .sort()
    expect(actual).toEqual(
      [
        "GET /v1/health",
        "GET /v1/info",
        "GET /v1/config",
        "PUT /v1/config",
        "GET /v1/config/raw",
        "GET /v1/secrets",
        "POST /v1/secrets",
        "DELETE /v1/secrets",
        "GET /v1/agents",
        "GET /v1/skills",
        "GET /v1/memory",
        "GET /v1/memory/{target}",
        "POST /v1/memory/{target}",
        "GET /v1/audit",
        "GET /v1/audit/stats",
        "GET /v1/sessions",
        "GET /v1/sessions/{instance}/{base}",
        "GET /v1/sessions/{instance}/{base}/export",
        "GET /v1/sessions/{instance}/{base}/context",
        "DELETE /v1/sessions/{instance}/{base}",
        "GET /v1/mcp",
        "GET /v1/models",
        "POST /v1/models/probe",
        "GET /v1/usage",
      ].sort(),
    )
    // The docs surface documents itself? No — the plugin excludes its own routes.
    expect(spec.paths?.["/openapi"]).toBeUndefined()
    expect(spec.paths?.["/openapi/json"]).toBeUndefined()
  })

  test("path params, query params and request bodies are documented", async () => {
    const spec = (await (await makeApp().handle(new Request("http://localhost/openapi/json"))).json()) as {
      paths?: Record<string, Record<string, Operation>>
    }
    const op = (path: string, method: string): Operation => spec.paths?.[path]?.[method] as Operation
    const param = (operation: Operation, name: string) => operation.parameters?.find((p) => p.name === name)

    // Sessions: path + query params, and a format enum on export.
    const listSessions = op("/v1/sessions", "get")
    expect(param(listSessions, "limit")?.in).toBe("query")
    expect(param(listSessions, "offset")?.in).toBe("query")
    const getSession = op("/v1/sessions/{instance}/{base}", "get")
    expect(param(getSession, "instance")?.in).toBe("path")
    expect(param(getSession, "base")?.in).toBe("path")
    expect(param(getSession, "instance")?.required).toBe(true)
    const exportSession = op("/v1/sessions/{instance}/{base}/export", "get")
    expect(param(exportSession, "format")?.schema?.enum).toEqual(["md", "jsonl"])

    // Memory: the target enum is documented on the path param.
    const getMemory = op("/v1/memory/{target}", "get")
    expect(param(getMemory, "target")?.schema?.enum).toEqual(["memory", "host", "journal"])
    const editMemory = op("/v1/memory/{target}", "post")
    expect(isTyped(editMemory.requestBody?.content?.["application/json"]?.schema)).toBe(true)
    expect(editMemory.requestBody?.content?.["application/json"]?.schema?.properties?.["action"]).toBeDefined()

    // Audit: the filter params, plus the format enum only on the list route.
    const listAudit = op("/v1/audit", "get")
    for (const name of ["since", "until", "session", "tool", "kind", "limit", "cursor", "format"]) {
      expect(param(listAudit, name), `audit list missing ${name}`).toBeDefined()
    }
    expect(param(listAudit, "format")?.schema?.enum).toEqual(["json", "jsonl", "csv"])
    const stats = op("/v1/audit/stats", "get")
    expect(param(stats, "since")).toBeDefined()
    expect(param(stats, "format")).toBeUndefined()

    // Settings writes: config mode query + free-form body, secret bodies/query.
    const putConfig = op("/v1/config", "put")
    expect(param(putConfig, "mode")?.in).toBe("query")
    expect(isTyped(putConfig.requestBody?.content?.["application/json"]?.schema)).toBe(true)
    const setSecret = op("/v1/secrets", "post")
    expect(setSecret.requestBody?.content?.["application/json"]?.schema?.required).toEqual(["name", "value"])
    const deleteSecret = op("/v1/secrets", "delete")
    expect(param(deleteSecret, "name")?.in).toBe("query")

    // The audit list documents all three export media types.
    expect(Object.keys(listAudit.responses?.["200"]?.content ?? {}).sort()).toEqual([
      "application/json",
      "application/x-ndjson",
      "text/csv",
    ])

    // The draft-endpoint probe documents its body and the no-key guarantee.
    const probe = op("/v1/models/probe", "post")
    const probeBody = probe.requestBody?.content?.["application/json"]?.schema
    expect(isTyped(probeBody)).toBe(true)
    expect(probeBody?.properties?.["apiKey"]).toBeDefined()
    expect(probeBody?.properties?.["baseURL"]).toBeDefined()
    expect(probeBody?.properties?.["provider"]).toBeDefined()
  })

  test("core response schemas match the actual payload keys", async () => {
    const app = makeApp()
    const spec = (await (await app.handle(new Request("http://localhost/openapi/json"))).json()) as {
      paths?: Record<string, Record<string, Operation>>
    }
    const auth = { authorization: `Bearer ${TOKEN}` }

    const healthSchema = spec.paths?.["/v1/health"]?.get?.responses?.["200"]?.content?.["application/json"]?.schema
    const health = (await (await app.handle(new Request("http://localhost/v1/health", { headers: auth }))).json()) as Record<string, unknown>
    expect(Object.keys(health).sort()).toEqual(Object.keys(healthSchema?.properties ?? {}).sort())

    const infoSchema = spec.paths?.["/v1/info"]?.get?.responses?.["200"]?.content?.["application/json"]?.schema
    const info = (await (await app.handle(new Request("http://localhost/v1/info", { headers: auth }))).json()) as Record<string, unknown>
    expect(Object.keys(info).sort()).toEqual(Object.keys(infoSchema?.properties ?? {}).sort())

    // A query that the handler rejects stays a `400 invalid_request` (the
    // permissive string schemas never turn it into a 422).
    const badLimit = await app.handle(new Request("http://localhost/v1/sessions?limit=abc", { headers: auth }))
    expect(badLimit.status).toBe(400)
    expect(await badLimit.json()).toEqual({ error: "invalid_request" })

    // A documented format enum that is not enforced at the schema layer still
    // reaches the handler and returns its own 400.
    const badFormat = await app.handle(new Request("http://localhost/v1/audit?format=bogus", { headers: auth }))
    expect(badFormat.status).toBe(400)
    expect(await badFormat.json()).toEqual({ error: "invalid_request" })
  })
})
