/**
 * Regenerate the README interface SVGs from the built sensus.sh landing page.
 *
 * The landing page's hero mock (site/src/components/TerminalMock.astro) is a
 * CSS-only recreation of the TUI, so the README captures are generated by
 * rendering that page in headless Chrome and serializing the `.mock` figure to
 * standalone SVG (rects/paths/text only; no <image> or <foreignObject>).
 *
 * Usage (from site/): `bun run readme-svg` rebuilds dist/ first;
 * `bun run readme-svg -- --no-build` reuses the existing build.
 *
 * Outputs (repo root): assets/ui.svg (sidebar + sshd) and
 * assets/ui-topbar-disk.svg (topbar + disk). The output is deterministic (no
 * timestamps or randomness) and pretty-printed one element per line so diffs
 * stay readable.
 */
import { existsSync } from "node:fs"
import { mkdir, mkdtemp, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const SITE_DIR = resolve(SCRIPT_DIR, "..")
const REPO_DIR = resolve(SITE_DIR, "..")
const ASSETS_DIR = join(REPO_DIR, "assets")
const CHROME = process.env.CHROME_PATH ?? "/usr/bin/google-chrome"

/** The emulated viewport; the `.mock` figure lands at ~1120px wide here. */
const VIEWPORT = { width: 1280, height: 900 } as const

interface Variant {
  /** Output file name under assets/. */
  readonly file: string
  /** Accessible label for the generated <svg role="img">. */
  readonly label: string
  /** Radio id for the layout (`#mock-view-sidebar` / `#mock-view-topbar`). */
  readonly layout: string
  /** Radio id for the session (`#ex-sshd` / `#ex-logs` / `#ex-disk`). */
  readonly session: string
}

const VARIANTS: readonly Variant[] = [
  {
    file: "ui.svg",
    label:
      "The sensus interface: the tabs rail, the terminal running an sshd hardening session, and the agent chat sidebar",
    layout: "mock-view-sidebar",
    session: "ex-sshd",
  },
  {
    file: "ui-topbar-disk.svg",
    label:
      "The sensus interface with the tab bar along the top: the terminal showing a full root disk and the agent chat sidebar",
    layout: "mock-view-topbar",
    session: "ex-disk",
  },
]

/* -------------------------------------------------------------------------- */
/* The in-page serializer                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Source of the function evaluated in the page to turn the live `.mock` figure
 * into one SVG string. Kept as a plain source string (not `fn.toString()`)
 * because Bun transpiles the file: the string is what actually runs in Chrome.
 *
 * Design notes:
 * - We emulate `prefers-reduced-motion: reduce` (see main()) because every
 *   entrance animation in the mock is gated on `no-preference`; with reduce the
 *   page is already in its stable final state and no composited layers linger.
 * - Text is walked one character at a time with `Range`. A single text node can
 *   wrap across several visual lines (the chat prose), and per-character rects
 *   are the only reliable way to recover those line breaks; a whole-node rect
 *   would give one giant box. Characters are grouped into lines by `top`.
 * - A per-character Range rect is exactly the font's ascent+descent box, so the
 *   baseline is `rect.top + ascent`, with ascent measured once per font via a
 *   canvas `measureText("Hg").fontBoundingBoxAscent`.
 * - Paint order is DOM order: each element's own background/border first, then
 *   its child nodes, so absolutely positioned children such as `.card-title`
 *   cover the parent's border like they do on the page.
 */
const SERIALIZE_MOCK = String.raw`
function serializeMock(label) {
  "use strict";

  const figure = document.querySelector(".mock");
  if (!figure) throw new Error("serializeMock: .mock figure not found");

  const MARGIN = 20;
  const figRect = figure.getBoundingClientRect();
  const width = figRect.width + MARGIN * 2;
  const height = figRect.height + MARGIN * 2;
  const dx = MARGIN - figRect.left;
  const dy = MARGIN - figRect.top;
  const bodyBg = getComputedStyle(document.body).backgroundColor;

  const out = [];

  function fmt(n) {
    return String(Math.round(n * 100) / 100);
  }

  function escText(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }

  function escAttr(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");
  }

  // Computed colors are rgb()/rgba(); treat anything unparseable as opaque.
  function colorAlpha(value) {
    const m = /^rgba?\(([^)]+)\)$/.exec(value);
    if (!m) return 0;
    const parts = m[1].split(",");
    if (parts.length < 4) return 1;
    const a = parseFloat(parts[3]);
    return isNaN(a) ? 1 : a;
  }

  function uniformRadius(cs) {
    const r = [
      cs.borderTopLeftRadius,
      cs.borderTopRightRadius,
      cs.borderBottomRightRadius,
      cs.borderBottomLeftRadius,
    ].map((v) => parseFloat(v) || 0);
    return r[0] === r[1] && r[1] === r[2] && r[2] === r[3] ? r[0] : 0;
  }

  // Chrome normalizes the mock's stepped panel corners to px in some builds
  // (polygon(4px 0px, 1116px 0px, ...)), but 152 keeps calc() unresolved, so
  // resolve px, %, and the calc(100% - Npx) form ourselves.
  function resolveCoord(token, size) {
    if (token === "0") return 0;
    let m = /^(-?[0-9.]+)(px|%)$/.exec(token);
    if (m) {
      const n = parseFloat(m[1]);
      return m[2] === "%" ? (size * n) / 100 : n;
    }
    m = /^calc\(\s*(-?[0-9.]+)%\s*([+-])\s*(-?[0-9.]+)px\s*\)$/.exec(token);
    if (m) {
      const base = (size * parseFloat(m[1])) / 100;
      const delta = parseFloat(m[3]);
      return m[2] === "-" ? base - delta : base + delta;
    }
    return null;
  }

  function polygonPoints(value, rect) {
    const m = /^polygon\(([\s\S]*)\)$/.exec(value.trim());
    if (!m) return null;
    // Each vertex is two coordinate expressions separated by whitespace; the
    // expressions themselves may contain spaces (calc(100% - 4px)), so match
    // them as a pair instead of splitting on whitespace.
    const coord = "(calc\\([^)]*\\)|-?[0-9.]+(?:px|%)|0)";
    const pair = new RegExp("^" + coord + "\\s+" + coord + "$");
    const points = [];
    for (const token of m[1].split(",")) {
      const pm = pair.exec(token.trim());
      if (!pm) return null;
      const x = resolveCoord(pm[1], rect.width);
      const y = resolveCoord(pm[2], rect.height);
      if (x === null || y === null) return null;
      points.push([x, y]);
    }
    return points.length >= 3 ? points : null;
  }

  function emitBackground(el, cs, rect) {
    const bg = cs.backgroundColor;
    if (colorAlpha(bg) <= 0.001) return;
    const caret = el.classList && el.classList.contains("caret");
    const clip = cs.clipPath;
    if (clip && clip !== "none") {
      const points = polygonPoints(clip, rect);
      if (points) {
        let d = "";
        for (let i = 0; i < points.length; i++) {
          d += (i === 0 ? "M " : "L ") + fmt(rect.left + points[i][0]) + " " + fmt(rect.top + points[i][1]) + " ";
        }
        d += "Z";
        out.push('<path d="' + d + '" fill="' + escAttr(bg) + '"' + (caret ? ' class="caret"' : "") + "/>");
        return;
      }
    }
    const radius = uniformRadius(cs);
    out.push(
      '<rect x="' + fmt(rect.left) + '" y="' + fmt(rect.top) + '" width="' + fmt(rect.width) + '" height="' + fmt(rect.height) + '"' +
        (radius > 0 ? ' rx="' + fmt(radius) + '"' : "") +
        ' fill="' + escAttr(bg) + '"' + (caret ? ' class="caret"' : "") + "/>"
    );
  }

  function emitBorder(cs, rect) {
    const sides = [
      { side: "top", width: parseFloat(cs.borderTopWidth) || 0, style: cs.borderTopStyle, color: cs.borderTopColor },
      { side: "right", width: parseFloat(cs.borderRightWidth) || 0, style: cs.borderRightStyle, color: cs.borderRightColor },
      { side: "bottom", width: parseFloat(cs.borderBottomWidth) || 0, style: cs.borderBottomStyle, color: cs.borderBottomColor },
      { side: "left", width: parseFloat(cs.borderLeftWidth) || 0, style: cs.borderLeftStyle, color: cs.borderLeftColor },
    ];
    const visible = sides.filter(
      (s) => s.width > 0 && s.style !== "none" && s.style !== "hidden" && colorAlpha(s.color) > 0.001
    );
    if (!visible.length) return;

    let uniform = visible.length === 4;
    for (let i = 1; i < visible.length; i++) {
      if (Math.abs(visible[i].width - visible[0].width) > 0.001 || visible[i].color !== visible[0].color) uniform = false;
    }

    if (uniform) {
      // A uniform border is one stroked rect inset by half the border width.
      const w = visible[0].width;
      const radius = uniformRadius(cs);
      const rx = radius > 0 ? Math.max(radius - w / 2, 0) : 0;
      out.push(
        '<rect x="' + fmt(rect.left + w / 2) + '" y="' + fmt(rect.top + w / 2) + '" width="' + fmt(Math.max(rect.width - w, 0)) + '" height="' + fmt(Math.max(rect.height - w, 0)) + '"' +
          (rx > 0 ? ' rx="' + fmt(rx) + '"' : "") +
          ' fill="none" stroke="' + escAttr(visible[0].color) + '" stroke-width="' + fmt(w) + '"/>'
      );
      return;
    }

    // Mixed sides (none in the current mock): one center line per side.
    for (const s of visible) {
      const half = s.width / 2;
      let x1 = rect.left;
      let y1 = rect.top;
      let x2 = rect.right;
      let y2 = rect.bottom;
      if (s.side === "top") {
        y1 = y2 = rect.top + half;
      } else if (s.side === "bottom") {
        y1 = y2 = rect.bottom - half;
      } else if (s.side === "left") {
        x1 = x2 = rect.left + half;
      } else {
        x1 = x2 = rect.right - half;
      }
      out.push(
        '<line x1="' + fmt(x1) + '" y1="' + fmt(y1) + '" x2="' + fmt(x2) + '" y2="' + fmt(y2) + '" stroke="' + escAttr(s.color) + '" stroke-width="' + fmt(s.width) + '"/>'
      );
    }
  }

  // Ascent is cached per computed font shorthand; the canvas resolves the same
  // family fallbacks the page used.
  const ascentCanvas = document.createElement("canvas");
  const ascentCtx = ascentCanvas.getContext("2d");
  const ascentCache = Object.create(null);
  function ascentFor(font, fontSize) {
    if (font in ascentCache) return ascentCache[font];
    let ascent = 0;
    if (ascentCtx) {
      ascentCtx.font = font;
      const m = ascentCtx.measureText("Hg");
      if (typeof m.fontBoundingBoxAscent === "number" && m.fontBoundingBoxAscent > 0) ascent = m.fontBoundingBoxAscent;
      else if (typeof m.actualBoundingBoxAscent === "number" && m.actualBoundingBoxAscent > 0) ascent = m.actualBoundingBoxAscent;
    }
    if (!ascent) ascent = fontSize * 0.8;
    ascentCache[font] = ascent;
    return ascent;
  }

  function flushLine(line, cs, ascent) {
    if (!line || !/\S/.test(line.text)) return;
    if (colorAlpha(cs.color) <= 0.001) return; // color: transparent (inactive tab markers)
    const textWidth = line.maxRight - line.minLeft;
    if (!(textWidth > 0)) return;
    let attrs =
      'x="' + fmt(line.minLeft) + '" y="' + fmt(line.top + ascent) + '" fill="' + escAttr(cs.color) + '"' +
      ' font-family="' + escAttr(cs.fontFamily) + '" font-size="' + cs.fontSize + '" font-weight="' + cs.fontWeight + '"';
    if (cs.letterSpacing && cs.letterSpacing !== "normal") attrs += ' letter-spacing="' + escAttr(cs.letterSpacing) + '"';
    attrs += ' textLength="' + fmt(textWidth) + '" lengthAdjust="spacingAndGlyphs" xml:space="preserve"';
    out.push("<text " + attrs + ">" + escText(line.text) + "</text>");
  }

  function emitTextNode(node) {
    const text = node.nodeValue || "";
    if (!/\S/.test(text)) return;
    const parent = node.parentElement;
    if (!parent) return;
    const cs = getComputedStyle(parent);
    // Collapsing whitespace (normal/nowrap/pre-line) renders a whole ASCII
    // whitespace run as one space, and Chrome gives most of that run zero-size
    // Range rects; remember the run and materialize exactly one space before
    // the next glyph. NBSP is not collapsible, so it goes through the glyph
    // path and keeps its real width.
    const collapsing = /^(normal|nowrap|pre-line)$/.test(cs.whiteSpace);
    const ascent = ascentFor(cs.font, parseFloat(cs.fontSize) || 0);
    const range = document.createRange();
    let line = null;
    for (let i = 0; i < text.length; i++) {
      const ch = text.charAt(i);
      range.setStart(node, i);
      range.setEnd(node, i + 1);
      const r = range.getBoundingClientRect();
      const zero = r.width === 0 && r.height === 0;
      if (/[ \t\n\r\f]/.test(ch) && collapsing) {
        if (line) line.pendingSpace = true;
        continue;
      }
      if (zero) continue;
      if (!line || Math.abs(r.top - line.top) > 0.5) {
        flushLine(line, cs, ascent);
        line = { top: r.top, minLeft: r.left, maxRight: r.right, text: ch, pendingSpace: false };
      } else {
        if (line.pendingSpace) {
          line.text += " ";
          line.pendingSpace = false;
        }
        if (r.left < line.minLeft) line.minLeft = r.left;
        if (r.right > line.maxRight) line.maxRight = r.right;
        line.text += ch;
      }
    }
    flushLine(line, cs, ascent);
  }

  function walk(el) {
    const cs = getComputedStyle(el);
    if (cs.display === "none" || cs.visibility === "hidden" || cs.visibility === "collapse") return;
    if (parseFloat(cs.opacity) < 0.01) return;
    const rect = el.getBoundingClientRect();
    if (rect.width <= 0 || rect.height <= 0) return;
    emitBackground(el, cs, rect);
    emitBorder(cs, rect);
    const nodes = el.childNodes;
    for (let i = 0; i < nodes.length; i++) {
      const node = nodes[i];
      if (node.nodeType === 3) emitTextNode(node); // TEXT_NODE
      else if (node.nodeType === 1) walk(node); // ELEMENT_NODE
    }
  }

  walk(figure);

  const parts = [];
  parts.push('<?xml version="1.0" encoding="UTF-8"?>');
  parts.push("<!--");
  parts.push("  README interface SVG: generated by site/scripts/readme-svg.ts from");
  parts.push("  site/src/components/TerminalMock.astro (the sensus.sh landing page mock).");
  parts.push("  Do not edit by hand; run \"bun run readme-svg\" in site/ to regenerate.");
  parts.push("-->");
  parts.push(
    '<svg xmlns="http://www.w3.org/2000/svg" width="' + fmt(width) + '" height="' + fmt(height) + '" viewBox="0 0 ' + fmt(width) + " " + fmt(height) + '" role="img" aria-label="' + escAttr(label) + '">'
  );
  parts.push("  <style>");
  parts.push("    .caret { animation: blink 1.15s steps(2, start) infinite; }");
  parts.push("    @keyframes blink { 0%, 49% { opacity: 1; } 50%, 100% { opacity: 0; } }");
  parts.push("    @media (prefers-reduced-motion: reduce) { .caret { animation: none; } }");
  parts.push("  </style>");
  parts.push('  <rect width="' + fmt(width) + '" height="' + fmt(height) + '" fill="' + escAttr(bodyBg) + '"/>');
  parts.push('  <g transform="translate(' + fmt(dx) + " " + fmt(dy) + ')">');
  for (const element of out) parts.push("    " + element);
  parts.push("  </g>");
  parts.push("</svg>");
  return parts.join("\n") + "\n";
}
`

/* -------------------------------------------------------------------------- */
/* A minimal CDP client                                                       */
/* -------------------------------------------------------------------------- */

interface CdpResponse {
  id?: number
  method?: string
  params?: unknown
  result?: unknown
  error?: { code: number; message: string }
}

type CdpHandler = (params: unknown) => void

class CdpClient {
  private readonly socket: WebSocket
  private nextId = 1
  private readonly pending = new Map<number, { resolve: (value: unknown) => void; reject: (error: Error) => void }>()
  private readonly handlers = new Map<string, Set<CdpHandler>>()

  private constructor(socket: WebSocket) {
    this.socket = socket
    socket.addEventListener("message", (event) => {
      const text = typeof event.data === "string" ? event.data : ""
      if (!text) return
      let message: CdpResponse
      try {
        message = JSON.parse(text) as CdpResponse
      } catch {
        return
      }
      if (typeof message.id === "number") {
        const pending = this.pending.get(message.id)
        if (!pending) return
        this.pending.delete(message.id)
        if (message.error) pending.reject(new Error(`CDP error ${message.error.code}: ${message.error.message}`))
        else pending.resolve(message.result)
        return
      }
      if (typeof message.method === "string") {
        const set = this.handlers.get(message.method)
        if (!set) return
        for (const handler of [...set]) handler(message.params)
      }
    })
    socket.addEventListener("close", () => {
      for (const [, pending] of this.pending) pending.reject(new Error("CDP connection closed"))
      this.pending.clear()
    })
  }

  static connect(url: string, timeoutMs = 15_000): Promise<CdpClient> {
    return new Promise((resolvePromise, rejectPromise) => {
      const socket = new WebSocket(url)
      const timer = setTimeout(() => {
        socket.close()
        rejectPromise(new Error(`Timed out connecting to ${url}`))
      }, timeoutMs)
      socket.addEventListener(
        "open",
        () => {
          clearTimeout(timer)
          resolvePromise(new CdpClient(socket))
        },
        { once: true },
      )
      socket.addEventListener(
        "error",
        () => {
          clearTimeout(timer)
          rejectPromise(new Error(`WebSocket error connecting to ${url}`))
        },
        { once: true },
      )
    })
  }

  send<T = unknown>(method: string, params?: Record<string, unknown>): Promise<T> {
    const id = this.nextId++
    return new Promise<T>((resolvePromise, rejectPromise) => {
      this.pending.set(id, { resolve: (value) => resolvePromise(value as T), reject: rejectPromise })
      try {
        this.socket.send(JSON.stringify({ id, method, params: params ?? {} }))
      } catch (error) {
        this.pending.delete(id)
        rejectPromise(error instanceof Error ? error : new Error(String(error)))
      }
    })
  }

  once(method: string, timeoutMs = 30_000): Promise<unknown> {
    return new Promise((resolvePromise, rejectPromise) => {
      const set = this.handlers.get(method) ?? new Set<CdpHandler>()
      this.handlers.set(method, set)
      const handler: CdpHandler = (params) => {
        clearTimeout(timer)
        set.delete(handler)
        resolvePromise(params)
      }
      const timer = setTimeout(() => {
        set.delete(handler)
        rejectPromise(new Error(`Timed out waiting for CDP event ${method}`))
      }, timeoutMs)
      set.add(handler)
    })
  }

  async evaluate(expression: string, options: { awaitPromise?: boolean } = {}): Promise<unknown> {
    const result = await this.send<{ result?: { value?: unknown }; exceptionDetails?: unknown }>("Runtime.evaluate", {
      expression,
      returnByValue: true,
      awaitPromise: options.awaitPromise ?? false,
    })
    if (result.exceptionDetails) {
      throw new Error(`Page evaluation failed: ${JSON.stringify(result.exceptionDetails).slice(0, 2000)}`)
    }
    return result.result?.value
  }

  close(): void {
    try {
      this.socket.close()
    } catch {
      // already closed
    }
  }
}

/* -------------------------------------------------------------------------- */
/* Static file server, Chrome launch, and the capture flow                    */
/* -------------------------------------------------------------------------- */

/** Serve `site/dist` with Bun.file's inferred content types; everything else 404s. */
function createStaticHandler(distDir: string): (request: Request) => Promise<Response> {
  return async (request) => {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method Not Allowed", { status: 405 })
    }
    let pathname: string
    try {
      pathname = decodeURIComponent(new URL(request.url).pathname)
    } catch {
      return new Response("Bad Request", { status: 400 })
    }
    if (pathname.endsWith("/")) pathname += "index.html"
    const filePath = resolve(distDir, "." + pathname)
    if (filePath !== distDir && !filePath.startsWith(distDir + sep)) {
      return new Response("Not Found", { status: 404 })
    }
    const file = Bun.file(filePath)
    if (!(await file.exists())) return new Response("Not Found", { status: 404 })
    return new Response(file, { headers: { "content-type": file.type || "application/octet-stream" } })
  }
}

interface ChromeHandle {
  readonly process: Bun.Subprocess
  readonly wsUrl: string
  readonly userDataDir: string
}

/** Read Chrome's stderr until the `DevTools listening on ws://...` line appears. */
async function waitForDevToolsUrl(stderr: ReadableStream<Uint8Array>, timeoutMs = 20_000): Promise<string> {
  const decoder = new TextDecoder()
  let buffer = ""
  let found = false
  const urlPromise = new Promise<string>((resolvePromise, rejectPromise) => {
    void (async () => {
      const reader = stderr.getReader()
      try {
        for (;;) {
          const { done, value } = await reader.read()
          if (done) break
          if (found) continue // keep draining so Chrome never blocks on a full pipe
          buffer += decoder.decode(value, { stream: true })
          const match = /DevTools listening on (ws:\/\/\S+)/.exec(buffer)
          if (match) {
            found = true
            resolvePromise(match[1])
          }
        }
        if (!found) rejectPromise(new Error(`Chrome exited before its DevTools URL appeared.\n${buffer.slice(-2000)}`))
      } catch (error) {
        if (!found) rejectPromise(error instanceof Error ? error : new Error(String(error)))
      }
    })()
  })
  let timer: ReturnType<typeof setTimeout> | undefined
  const timeoutPromise = new Promise<never>((_, rejectPromise) => {
    timer = setTimeout(() => rejectPromise(new Error("Timed out waiting for Chrome's DevTools URL")), timeoutMs)
  })
  try {
    return await Promise.race([urlPromise, timeoutPromise])
  } finally {
    if (timer !== undefined) clearTimeout(timer)
  }
}

async function launchChrome(pageUrl: string): Promise<ChromeHandle> {
  if (!existsSync(CHROME)) throw new Error(`Chrome not found at ${CHROME}; set CHROME_PATH to override`)
  const userDataDir = await mkdtemp(join(tmpdir(), "sensus-readme-svg-"))
  const args = [
    "--headless=new",
    "--remote-debugging-port=0",
    `--user-data-dir=${userDataDir}`,
    "--no-first-run",
    "--no-default-browser-check",
    "--disable-gpu",
    "--hide-scrollbars",
    "--force-device-scale-factor=1",
  ]
  // Chrome refuses to start as root without --no-sandbox (containers/CI).
  if (process.getuid?.() === 0) args.push("--no-sandbox")
  args.push(pageUrl)
  const chromeProcess = Bun.spawn([CHROME, ...args], { stdout: "ignore", stderr: "pipe" })
  try {
    const stderr = chromeProcess.stderr
    if (!stderr || typeof stderr === "number") throw new Error("Chrome stderr was not piped")
    const wsUrl = await waitForDevToolsUrl(stderr)
    return { process: chromeProcess, wsUrl, userDataDir }
  } catch (error) {
    // Never leave a half-launched Chrome behind if the handshake fails.
    try {
      chromeProcess.kill()
    } catch {
      // already gone
    }
    try {
      await rm(userDataDir, { recursive: true, force: true })
    } catch {
      // best effort
    }
    throw error
  }
}

interface CdpTarget {
  type?: string
  url?: string
  webSocketDebuggerUrl?: string
}

/** Poll /json/list until the launched page target exposes its WS endpoint. */
async function waitForPageTarget(debugPort: number, pageUrl: string, timeoutMs = 15_000): Promise<string> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    try {
      const response = await fetch(`http://127.0.0.1:${debugPort}/json/list`)
      if (response.ok) {
        const targets = (await response.json()) as CdpTarget[]
        const page =
          targets.find(
            (target) => target.type === "page" && typeof target.webSocketDebuggerUrl === "string" && target.url?.startsWith(pageUrl),
          ) ?? targets.find((target) => target.type === "page" && typeof target.webSocketDebuggerUrl === "string")
        if (page?.webSocketDebuggerUrl) return page.webSocketDebuggerUrl
      }
    } catch {
      // DevTools endpoint not up yet.
    }
    if (Date.now() > deadline) throw new Error("Timed out waiting for a Chrome page target")
    await Bun.sleep(50)
  }
}

/** Wait for system fonts and the `.mock` figure to be ready. */
async function waitForMockReady(cdp: CdpClient, timeoutMs = 15_000): Promise<void> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    const ready = await cdp.evaluate('document.fonts.status === "loaded" && document.querySelector(".mock") !== null')
    if (ready === true) return
    if (Date.now() > deadline) throw new Error("Timed out waiting for fonts and the .mock figure")
    await Bun.sleep(50)
  }
}

/** Check the radios that drive the CSS-only mock, then let layout settle. */
async function selectVariant(cdp: CdpClient, variant: Variant): Promise<void> {
  await cdp.evaluate(
    "(() => {" +
      " const layout = document.getElementById(" + JSON.stringify(variant.layout) + ");" +
      " const session = document.getElementById(" + JSON.stringify(variant.session) + ");" +
      " if (!layout || !session) throw new Error('mock radios missing');" +
      " layout.checked = true; session.checked = true; return true;" +
      " })()",
  )
  await cdp.evaluate("new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve(true))))", {
    awaitPromise: true,
  })
}

/* -------------------------------------------------------------------------- */
/* Lifecycle                                                                  */
/* -------------------------------------------------------------------------- */

let activeChrome: ChromeHandle | undefined
let activeServer: ReturnType<typeof Bun.serve> | undefined

async function waitForExit(process: Bun.Subprocess, timeoutMs: number): Promise<boolean> {
  let timer: ReturnType<typeof setTimeout> | undefined
  const timeout = new Promise<boolean>((resolvePromise) => {
    timer = setTimeout(() => resolvePromise(false), timeoutMs)
  })
  try {
    return await Promise.race([process.exited.then(() => true), timeout])
  } finally {
    if (timer !== undefined) clearTimeout(timer)
  }
}

/** Kill Chrome, delete its profile dir, and stop the static server. Idempotent. */
async function cleanup(): Promise<void> {
  const chrome = activeChrome
  activeChrome = undefined
  if (chrome) {
    try {
      chrome.process.kill()
    } catch {
      // already gone
    }
    if (!(await waitForExit(chrome.process, 5_000))) {
      try {
        chrome.process.kill("SIGKILL")
      } catch {
        // already gone
      }
    }
    try {
      await rm(chrome.userDataDir, { recursive: true, force: true })
    } catch {
      // best effort
    }
  }
  const server = activeServer
  activeServer = undefined
  if (server) server.stop(true)
}

export async function main(argv: readonly string[] = process.argv.slice(2)): Promise<void> {
  const rebuild = !argv.includes("--no-build")

  if (rebuild) {
    console.log("readme-svg: building site/ (bun run build)")
    const build = Bun.spawn(["bun", "run", "build"], { cwd: SITE_DIR, stdio: ["inherit", "inherit", "inherit"] })
    const exitCode = await build.exited
    if (exitCode !== 0) throw new Error(`site build failed with exit code ${exitCode}`)
  }

  const distDir = join(SITE_DIR, "dist")
  if (!existsSync(join(distDir, "index.html"))) {
    throw new Error(`missing ${join(distDir, "index.html")}; run "bun run build" in site/ first`)
  }

  activeServer = Bun.serve({ port: 0, hostname: "127.0.0.1", fetch: createStaticHandler(distDir) })
  const pageUrl = `http://127.0.0.1:${activeServer.port}/`

  const onSignal = (): void => {
    void cleanup().finally(() => process.exit(130))
  }
  process.once("SIGINT", onSignal)
  process.once("SIGTERM", onSignal)

  try {
    activeChrome = await launchChrome(pageUrl)
    const debugPort = Number(new URL(activeChrome.wsUrl).port)
    const pageSocketUrl = await waitForPageTarget(debugPort, pageUrl)
    const cdp = await CdpClient.connect(pageSocketUrl)
    try {
      await cdp.send("Page.enable")
      await cdp.send("Runtime.enable")
      await cdp.send("Emulation.setDeviceMetricsOverride", {
        width: VIEWPORT.width,
        height: VIEWPORT.height,
        deviceScaleFactor: 1,
        mobile: false,
      })
      // Force the dark palette and reduced motion. Every mock entrance is gated
      // on `prefers-reduced-motion: no-preference`, so reduce lands the page in
      // its final state with no animation layers for the capture.
      await cdp.send("Emulation.setEmulatedMedia", {
        features: [
          { name: "prefers-color-scheme", value: "dark" },
          { name: "prefers-reduced-motion", value: "reduce" },
        ],
      })

      // Reload so emulation applies from the first paint, then wait for load.
      const loaded = cdp.once("Page.loadEventFired")
      await cdp.send("Page.reload", { ignoreCache: true })
      await loaded
      await waitForMockReady(cdp)
      await Bun.sleep(100)

      await mkdir(ASSETS_DIR, { recursive: true })
      for (const variant of VARIANTS) {
        await selectVariant(cdp, variant)
        const svg = await cdp.evaluate(`(${SERIALIZE_MOCK})(${JSON.stringify(variant.label)})`)
        if (typeof svg !== "string" || !svg.startsWith("<?xml")) {
          throw new Error(`serializer did not return an SVG for ${variant.file}`)
        }
        const outPath = join(ASSETS_DIR, variant.file)
        await Bun.write(outPath, svg)
        console.log(`readme-svg: wrote ${outPath} (${new TextEncoder().encode(svg).byteLength} bytes)`)
      }
    } finally {
      cdp.close()
    }
  } finally {
    process.off("SIGINT", onSignal)
    process.off("SIGTERM", onSignal)
    await cleanup()
  }
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    console.error(`readme-svg: ${error instanceof Error ? (error.stack ?? error.message) : String(error)}`)
    process.exit(1)
  })
}
