/**
 * Machine/installation identity (D13; docs/events.md): `instance.json` under
 * the config home (`~/.config/sensus/instance.json`), owned and generated by
 * the daemon at boot. It carries a ULID-like stable `instanceId`, the epoch ms
 * of FIRST creation (`createdAt`), and the sensus `version` that last wrote it.
 *
 * Stability is the contract: an existing VALID file is never regenerated —
 * across restarts, upgrades, and version changes only the `version` field is
 * refreshed. The identity is repaired (regenerated) only when the file is
 * missing or corrupt, because a corrupt identity is worse than a new one.
 *
 * Every function here is defensive: it never throws and a write failure still
 * returns the in-memory instance (the daemon must boot even on a read-only
 * config home).
 */

import { readFileSync } from "node:fs"
import { randomBytes } from "node:crypto"
import { isRecord } from "../../core/util.ts"
import { atomicWriteText } from "../../core/util.ts"
import { instancePath } from "./paths.ts"

/** The identity document written to `<config-home>/instance.json`. */
export interface SensusInstance {
  /** ULID-like stable id (26 Crockford base32 chars). */
  instanceId: string
  /** Epoch ms of first creation; never changes once written. */
  createdAt: number
  /** The sensus version that last wrote the file (refreshed on upgrade). */
  version: string
}

/** Crockford base32 alphabet (ULID). */
const CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

/** Default randomness: 10 cryptographically strong bytes (80 bits). */
function defaultRandom(n: number): Uint8Array {
  return new Uint8Array(randomBytes(n))
}

/**
 * A ULID-like id: 10 chars of 48-bit millisecond time + 16 chars of 80-bit
 * randomness = 26 Crockford base32 chars, lexicographically sortable by time.
 * `random` is a test seam; production uses `crypto.randomBytes`.
 */
export function generateInstanceId(now: number = Date.now(), random: (n: number) => Uint8Array = defaultRandom): string {
  let t = Math.max(0, Math.floor(now))
  const time = new Array<string>(10)
  for (let i = 9; i >= 0; i--) {
    time[i] = CROCKFORD[t % 32] ?? "0"
    t = Math.floor(t / 32)
  }
  const bytes = random(10)
  let out = time.join("")
  let bits = 0
  let value = 0
  for (let i = 0; i < 10; i++) {
    value = (value << 8) | (bytes[i] ?? 0)
    bits += 8
    while (bits >= 5) {
      bits -= 5
      out += CROCKFORD[(value >>> bits) & 31] ?? "0"
    }
  }
  return out.slice(0, 26)
}

/** Validate a parsed value as an instance document; false for anything off. */
export function isSensusInstance(value: unknown): value is SensusInstance {
  if (!isRecord(value)) return false
  const { instanceId, createdAt, version } = value
  if (typeof instanceId !== "string" || instanceId.trim().length === 0) return false
  if (typeof createdAt !== "number" || !Number.isFinite(createdAt) || createdAt <= 0) return false
  if (typeof version !== "string") return false
  return true
}

/**
 * Read `<home>/instance.json`. Returns null when it is missing, unreadable,
 * not JSON, or structurally invalid (the caller repairs it).
 */
export function readInstance(home: string): SensusInstance | null {
  let text: string
  try {
    text = readFileSync(instancePath(home), "utf8")
  } catch {
    return null
  }
  try {
    const parsed: unknown = JSON.parse(text)
    return isSensusInstance(parsed) ? { instanceId: parsed.instanceId, createdAt: parsed.createdAt, version: parsed.version } : null
  } catch {
    return null
  }
}

/** Atomically persist the instance document. Never throws. */
function writeInstance(home: string, instance: SensusInstance): void {
  try {
    atomicWriteText(instancePath(home), JSON.stringify(instance, null, 2) + "\n")
  } catch {
    // A read-only/absent config home must not stop the daemon booting.
  }
}

/**
 * The identity contract: reuse a valid `instance.json` (refreshing only its
 * `version` when it changed), else generate + persist a new one. A corrupt
 * file is unconditionally replaced. Never throws.
 */
export function loadOrCreateInstance(home: string, version: string): SensusInstance {
  const existing = readInstance(home)
  if (existing !== null) {
    if (existing.version !== version) {
      const refreshed: SensusInstance = { instanceId: existing.instanceId, createdAt: existing.createdAt, version }
      writeInstance(home, refreshed)
      return refreshed
    }
    return existing
  }
  const created: SensusInstance = { instanceId: generateInstanceId(), createdAt: Date.now(), version }
  writeInstance(home, created)
  return created
}

/** The path helper re-exported for consumers that only need the location. */
export { instancePath }
